# Clippy configuration for oramacore-client

# Allow certain lints that are too strict for our use case
avoid-breaking-exported-api = false
cognitive-complexity-threshold = 50

# Disallowed methods and types (add any you want to prevent)
disallowed-methods = []
disallowed-types = []

# Performance optimizations
too-many-arguments-threshold = 10
type-complexity-threshold = 500
single-char-lifetime-names = true

# Documentation
doc-valid-idents = ["API", "JSON", "HTTP", "URL", "UUID", "AI", "ML", "LLM", "NLP", "CRUD"]