# Rustfmt configuration for oramacore-client

# Stable configuration options
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
reorder_imports = true
group_imports = "StdExternalCrate"

# Formatting
max_width = 100
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true

# Functions
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"

# Strings and arrays
array_width = 60
chain_width = 60

# Trailing commas
trailing_comma = "Vertical"